# Generated by Django 3.1.6 on 2021-09-07 17:02

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar\\default.jpg', upload_to=app01.models.user_directory_path, verbose_name='头像'),
        ),
    ]
