# Generated by Django 3.1.6 on 2021-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210419_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '处理中'), (1, '新建'), (5, '待反馈'), (7, '重新打开'), (6, '已关闭'), (4, '已忽略'), (3, '已解决')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (2, '收费版'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(3, '#ebc656'), (4, '#a2d148'), (7, '#20bfa3'), (6, '#7461c2'), (5, '#20bFA4'), (2, '#f28033'), (1, '#56b8eb')], default=1, verbose_name='颜色'),
        ),
    ]
