# Generated by Django 3.1.6 on 2021-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210705_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='mode',
            field=models.SmallIntegerField(choices=[(1, '公开模式'), (2, '隐私模式')], default=1, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('warning', '中'), ('danger', '高'), ('success', '低')], default='danger', max_length=12, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(4, '已忽略'), (6, '已关闭'), (7, '重新打开'), (5, '待反馈'), (3, '已解决'), (1, '新建'), (2, '处理中')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (3, '其他'), (2, '收费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(4, '#a2d148'), (2, '#f28033'), (7, '#20bfa3'), (5, '#20bFA4'), (3, '#ebc656'), (1, '#56b8eb'), (6, '#7461c2')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '未支付')], verbose_name='状态'),
        ),
    ]
