# Generated by Django 3.1.6 on 2021-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210705_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='mode',
            field=models.SmallIntegerField(choices=[(2, '隐私模式'), (1, '公开模式')], default=1, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(4, '已忽略'), (6, '已关闭'), (5, '待反馈'), (1, '新建'), (7, '重新打开'), (3, '已解决'), (2, '处理中')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#56b8eb'), (2, '#f28033'), (6, '#7461c2'), (4, '#a2d148'), (7, '#20bfa3'), (5, '#20bFA4'), (3, '#ebc656')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], verbose_name='状态'),
        ),
    ]
