# Generated by Django 3.1.6 on 2021-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210910_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('success', '低'), ('warning', '中'), ('danger', '高')], default='danger', max_length=12, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(4, '已忽略'), (5, '待反馈'), (2, '处理中'), (7, '重新打开'), (3, '已解决'), (6, '已关闭'), (1, '新建')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (3, '其他'), (2, '收费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(5, '#20bFA4'), (6, '#7461c2'), (4, '#a2d148'), (1, '#56b8eb'), (3, '#ebc656'), (7, '#20bfa3'), (2, '#f28033')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '未支付')], verbose_name='状态'),
        ),
    ]
