# Generated by Django 3.1.6 on 2021-09-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210914_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('danger', '高'), ('warning', '中'), ('success', '低')], default='danger', max_length=12, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '新建'), (4, '已忽略'), (6, '已关闭'), (5, '待反馈'), (3, '已解决'), (2, '处理中'), (7, '重新打开')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (2, '收费版'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(6, '#7461c2'), (2, '#f28033'), (1, '#56b8eb'), (5, '#20bFA4'), (7, '#20bfa3'), (3, '#ebc656'), (4, '#a2d148')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '未支付')], verbose_name='状态'),
        ),
    ]
