# Generated by Django 3.1.6 on 2021-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairparts',
            name='type',
            field=models.CharField(choices=[('4', '成型镶块'), ('0', '凹模'), ('3', '斜楔'), ('2', 'TD镶块'), ('1', '冲头'), ('5', '其它')], default='0', max_length=2, verbose_name='类型'),
        ),
    ]
