# Generated by Django 3.1.6 on 2021-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0002_auto_20210419_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('local', models.CharField(max_length=20, verbose_name='货位编号')),
                ('model', models.CharField(max_length=20, verbose_name='规格型号')),
                ('quantity', models.PositiveIntegerField(default=1, null=True, verbose_name='在库数量')),
            ],
            options={
                'db_table': 'm_specialparts',
            },
        ),
        migrations.AlterField(
            model_name='repairparts',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='repairparts',
            name='type',
            field=models.CharField(choices=[('1', '冲头'), ('2', 'TD镶块'), ('5', '其它'), ('4', '成型镶块'), ('3', '斜楔'), ('0', '凹模')], default='0', max_length=2, verbose_name='类型'),
        ),
    ]
