# Generated by Django 3.1.6 on 2021-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0005_auto_20210907_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairparts',
            name='type',
            field=models.CharField(choices=[('5', '其它'), ('0', '凹模'), ('3', '斜楔'), ('1', '冲头'), ('4', '成型镶块'), ('2', 'TD镶块')], default='0', max_length=2, verbose_name='类型'),
        ),
    ]
