# Generated by Django 3.1.6 on 2021-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0010_auto_20210914_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairparts',
            name='type',
            field=models.CharField(choices=[('4', '成型镶块'), ('3', '斜楔'), ('5', '其它'), ('2', 'TD镶块'), ('1', '冲头'), ('0', '凹模')], default='0', max_length=2, verbose_name='类型'),
        ),
    ]
