# Generated by Django 3.1.6 on 2021-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0012_auto_20210914_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairparts',
            name='type',
            field=models.CharField(choices=[('0', '凹模'), ('3', '斜楔'), ('1', '冲头'), ('4', '成型镶块'), ('2', 'TD镶块'), ('5', '其它')], default='0', max_length=2, verbose_name='类型'),
        ),
    ]
