# Generated by Django 3.1.6 on 2021-04-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=20, null=True, verbose_name='设备')),
                ('serial', models.CharField(blank=True, max_length=3, null=True, verbose_name='系列')),
                ('squeeze', models.CharField(blank=True, max_length=3, null=True, verbose_name='预压')),
                ('slope', models.CharField(blank=True, max_length=3, null=True, verbose_name='缓升')),
                ('weld1', models.CharField(blank=True, max_length=3, null=True, verbose_name='通电1')),
                ('cool1', models.CharField(blank=True, max_length=3, null=True, verbose_name='冷却1')),
                ('weld2', models.CharField(blank=True, max_length=3, null=True, verbose_name='通电2')),
                ('cool2', models.CharField(blank=True, max_length=3, null=True, verbose_name='冷却2')),
                ('weld3', models.CharField(blank=True, max_length=3, null=True, verbose_name='通电3')),
                ('dslope', models.CharField(blank=True, max_length=3, null=True, verbose_name='缓降')),
                ('hold', models.CharField(blank=True, max_length=3, null=True, verbose_name='保持')),
                ('heat1', models.CharField(blank=True, max_length=3, null=True, verbose_name='焊接1')),
                ('heat2', models.CharField(blank=True, max_length=3, null=True, verbose_name='焊接2')),
                ('heat3', models.CharField(blank=True, max_length=3, null=True, verbose_name='焊接3')),
                ('gauge', models.CharField(blank=True, max_length=3, null=True, verbose_name='表压力')),
                ('pressure', models.CharField(blank=True, max_length=3, null=True, verbose_name='加压力')),
            ],
            options={
                'db_table': 'w_parameters',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目')),
                ('part_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='零件号')),
                ('op', models.CharField(blank=True, max_length=20, null=True, verbose_name='工序')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称')),
                ('m1', models.CharField(blank=True, max_length=20, null=True, verbose_name='材料1')),
                ('t1', models.CharField(blank=True, max_length=20, null=True, verbose_name='厚度1')),
                ('m2', models.CharField(blank=True, max_length=20, null=True, verbose_name='材料2')),
                ('t2', models.CharField(blank=True, max_length=20, null=True, verbose_name='厚度2')),
                ('m3', models.CharField(blank=True, max_length=20, null=True, verbose_name='材料3')),
                ('t3', models.CharField(blank=True, max_length=20, null=True, verbose_name='厚度3')),
                ('diameter', models.CharField(blank=True, max_length=20, null=True, verbose_name='修磨直径（mm)')),
                ('frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='修磨频次')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('modify', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='修改者')),
                ('sc', models.ManyToManyField(to='welding.Parameters', verbose_name='参数')),
            ],
            options={
                'db_table': 'w_recipe',
            },
        ),
        migrations.AddField(
            model_name='parameters',
            name='part',
            field=models.ManyToManyField(to='welding.Recipe'),
        ),
    ]
