# Generated by Django 3.1.6 on 2021-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='spots',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='打点数'),
        ),
    ]
