# Generated by Django 3.1.6 on 2021-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0002_auto_20210910_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='serial',
            field=models.CharField(blank=True, choices=[('1', 'B-1'), ('2', 'B-2'), ('3', 'B-3'), ('4', 'B-4'), ('5', 'B-5'), ('6', 'B-6'), ('7', 'B-7'), ('8', 'B-8'), ('9', 'B-9'), ('A', 'B-A'), ('B', 'B-B'), ('C', 'B-C'), ('D', 'B-D'), ('E', 'B-E'), ('F', 'B-F')], max_length=3, null=True, verbose_name='系列'),
        ),
    ]
