# Generated by Django 3.1.6 on 2021-09-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0003_auto_20210910_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='part',
        ),
    ]
