# Generated by Django 3.1.6 on 2021-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0004_remove_parameters_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='etype',
            field=models.CharField(blank=True, choices=[('1', '上I下I'), ('2', '上L下I'), ('3', '上I下L'), ('4', '上L下L'), ('5', '其它')], max_length=3, null=True, verbose_name='握杆式样'),
        ),
    ]
