# Generated by Django 3.1.6 on 2021-09-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0006_parameters_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='eq_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='设备'),
        ),
    ]
