# Generated by Django 3.1.6 on 2021-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welding', '0008_auto_20210914_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='Prsquez',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='预压'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='squeeze',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='加压'),
        ),
    ]
